name: push
run-name: ${{ github.actor }} run Actions 🚀
on: workflow_dispatch
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install
        run: |
          echo "Start install"
      - name: build
        run: |
          echo "Start build"
